import { createFileRoute } from "@tanstack/react-router";
import type { ReactNode } from "react";

import { PublicAppShell } from "@/components/arc/PublicAppShell";

const TITLE = "About ARC — Ayden's Revenue Compass";
const DESCRIPTION =
  "What Ayden's Revenue Compass (ARC) is, how it separates AI interpretation from deterministic ASC 606 accounting, and the role of accountant judgment.";

export const Route = createFileRoute("/about")({
  head: () => ({
    meta: [
      { title: TITLE },
      { name: "description", content: DESCRIPTION },
      { property: "og:title", content: TITLE },
      { property: "og:description", content: DESCRIPTION },
      { property: "og:type", content: "website" },
      { name: "twitter:card", content: "summary" },
    ],
  }),
  component: AboutPage,
});

function Block({ title, children }: { title: string; children: ReactNode }) {
  return (
    <section className="space-y-2">
      <h2 className="text-lg font-semibold text-foreground">{title}</h2>
      <div className="space-y-2 text-sm leading-6 text-muted-foreground">{children}</div>
    </section>
  );
}

function AboutPage() {
  return (
    <PublicAppShell>
      <main className="mx-auto w-full max-w-3xl space-y-8 px-4 py-10 sm:px-6 sm:py-14">
        <header className="space-y-2">
          <h1 className="text-3xl font-bold text-foreground">About ARC</h1>
          <p className="text-sm leading-6 text-muted-foreground">
            ARC — Ayden&apos;s Revenue Compass — is an ASC 606 workpaper application. It takes a
            customer contract from review and accounting judgment through to deterministic
            outputs: performance-obligation analysis, transaction-price treatment, allocation,
            revenue schedules, contract balances and journal-entry workpapers. ARC supports the
            accountant&apos;s work; it does not replace it.
          </p>
        </header>

        <Block title="How ARC works">
          <p>
            ARC separates what a contract says from what the accounting requires, and assigns each
            part of the work to the party best suited to it.
          </p>
          <p>
            <strong className="text-foreground">AI interprets contract evidence.</strong> When a
            contract PDF is provided, AI helps identify the relevant contractual facts — parties,
            dates, promises, pricing and billing terms — and points to the passages that support
            them.
          </p>
          <p>
            <strong className="text-foreground">
              Deterministic accounting engines calculate results.
            </strong>{" "}
            Allocation, revenue schedules, contract balances and journal entries are computed by
            fixed application logic, not generated by the model. The same inputs always produce the
            same outputs.
          </p>
          <p>
            <strong className="text-foreground">The accountant owns the judgment.</strong> Every
            AI-drafted fact or conclusion remains reviewable and editable. Open review items
            require an explicit decision by the accountant before an analysis can be finalized.
          </p>
        </Block>

        <Block title="Accounting judgment, software discipline">
          <p>
            Revenue recognition depends on judgment, and judgment is only as reliable as the
            evidence behind it. ARC is built around that idea: conclusions stay tied to their
            source evidence, calculations are validated and reconcile across workpapers, and
            reviewable items are resolved explicitly rather than accepted silently.
          </p>
          <p>
            Where source evidence is insufficient, ARC stops and asks for review instead of
            filling the gap with an assumption. Automation assists the accountant, but control
            over the analysis stays with the accountant.
          </p>
        </Block>

        <Block title="A portfolio project">
          <p>
            ARC was built as a portfolio project to demonstrate how technical accounting and
            software can work together. It brings together ASC 606 application, product and
            workflow design, AI-assisted contract review, testing and validation of accounting
            logic, and the traceability that audit-ready work requires.
          </p>
        </Block>

        <Block title="Scope">
          <p>
            ARC is a portfolio and workpaper application. It is not a commercial accounting system
            and is not a substitute for professional accounting judgment. ARC prepares
            journal-entry workpapers, but it does not post entries to a general ledger, issue
            customer invoices or produce financial statements.
          </p>
        </Block>
      </main>
    </PublicAppShell>
  );
}
