import { createFileRoute, Link } from "@tanstack/react-router";

import { PublicAppShell } from "@/components/arc/PublicAppShell";
import { Button } from "@/components/ui/button";
const TITLE = "ASC 606 Analysis Platform — Ayden's Revenue Compass";
const DESCRIPTION =
  "Work from accountant-owned ASC 606 judgments through deterministic allocation, revenue schedules, contract balances and journal entries.";

const PRINCIPLES = [
  {
    title: "Accountant-owned judgments",
      description:
        "AI can draft the analysis, but professional judgment and control remain with the accountant.",
  },
  {
    title: "Deterministic calculations",
    description:
      "Allocation, schedules, balances and journals are calculated by tested accounting engines—not generated by AI.",
  },
  {
    title: "Traceable review",
    description:
        "Review AI-drafted conclusions, inspect source evidence and move from contract analysis to journal entry all in one workflow.",
  },
] as const;

const OUTPUTS = [
  "ASC 606 Analysis",
  "Revenue Schedule",
  "Contract Balances",
  "Journal Entries",
  "Review & Finalize",
] as const;

export const Route = createFileRoute("/")({
  head: () => ({
    meta: [
      { title: TITLE },
      { name: "description", content: DESCRIPTION },
      { property: "og:title", content: TITLE },
      { property: "og:description", content: DESCRIPTION },
      { property: "og:type", content: "website" },
      { property: "og:url", content: "/" },
      { name: "twitter:card", content: "summary" },
    ],
    links: [{ rel: "canonical", href: "/" }],
  }),
  component: Index,
});

function Index() {
  return (
    <PublicAppShell>
      <main className="mx-auto w-full max-w-6xl px-4 py-10 sm:px-6 sm:py-14">
        <header className="max-w-4xl">
          <p className="text-xs font-semibold uppercase text-primary">
            ARC · ASC 606 Analysis Platform
          </p>
          <h1 className="mt-4 text-3xl font-bold leading-tight text-foreground sm:text-5xl">
            ASC 606 analysis, from contract judgment to journal entry.
          </h1>
          <p className="mt-5 max-w-3xl text-base font-medium leading-7 text-foreground sm:text-lg">
            AI interprets the contract. Deterministic accounting engines calculate the results. You
            review and control the judgments.
          </p>
          <p className="mt-2 max-w-3xl text-sm leading-6 text-muted-foreground sm:text-base">
            Produce an auditable ASC 606 analysis from contract review through allocation, revenue
            schedules, balances and journal entries.
          </p>
        </header>

        <section aria-label="Get started" className="mt-9 grid gap-4 md:grid-cols-3">
          <article className="flex h-full flex-col border-t-2 border-primary bg-card p-5 sm:p-6">
            <p className="mb-2 text-xs font-semibold uppercase text-primary">Start here</p>
            <h2 className="text-lg font-semibold text-foreground">Try a Sample Contract</h2>
            <p className="mt-2 flex-1 text-sm leading-6 text-muted-foreground">
              Explore a fictional ASC 606 analysis using ARC&apos;s deterministic engines.
            </p>
            <Button asChild className="mt-5 w-fit">
              <Link to="/analysis" search={{ sample: "horizon" }}>
                Try the Sample
              </Link>
            </Button>
          </article>

          <article className="flex h-full flex-col border-t-2 border-border bg-card p-5 sm:p-6">
            <h2 className="text-lg font-semibold text-foreground">Upload a Contract PDF</h2>
            <p className="mt-2 flex-1 text-sm leading-6 text-muted-foreground">
              Upload a contract PDF. AI interprets the contract and sends the structured analysis to
              ARC’s deterministic accounting engines.
            </p>
            <Button asChild variant="outline" className="mt-5 w-fit">
              <Link to="/analysis" search={{ upload: "1" }}>
                Upload PDF
              </Link>
            </Button>
          </article>

          <article className="flex h-full flex-col border-t-2 border-border bg-card p-5 sm:p-6">
            <h2 className="text-lg font-semibold text-foreground">
              Enter Contract Details Manually
            </h2>
            <p className="mt-2 flex-1 text-sm leading-6 text-muted-foreground">
              Enter contract facts and accounting judgments directly in the ARC workspace.
            </p>
            <Button asChild variant="outline" className="mt-5 w-fit">
              <Link to="/analysis">Start Manually</Link>
            </Button>
          </article>
        </section>

        <section className="mt-10 border-t border-border pt-7">
          <div className="mb-5">
            <p className="text-xs font-semibold uppercase text-primary">Why ARC</p>
            <h2 className="mt-2 text-2xl font-semibold text-foreground">
              Built for accountable analysis
            </h2>
          </div>
          <div className="grid gap-px overflow-hidden rounded-lg border border-border bg-border md:grid-cols-3">
            {PRINCIPLES.map((principle) => (
              <article key={principle.title} className="bg-card p-5">
                <h3 className="text-sm font-semibold text-foreground">{principle.title}</h3>
                <p className="mt-2 text-sm leading-6 text-muted-foreground">
                  {principle.description}
                </p>
              </article>
            ))}
          </div>
        </section>

        <section className="mt-12 border-t border-border pt-8">
          <p className="text-xs font-semibold uppercase text-primary">Workpaper outputs</p>
          <h2 className="mt-2 text-2xl font-semibold text-foreground">What ARC produces</h2>
          <p className="mt-2 text-sm leading-6 text-muted-foreground">
            One connected workpaper from contract interpretation through accounting output.
          </p>
          <ul className="mt-5 grid gap-2 sm:grid-cols-2 lg:grid-cols-5">
            {OUTPUTS.map((output, index) => (
              <li key={output} className="border-l border-border py-2 pl-3">
                <span className="block text-xs tabular-nums text-muted-foreground">
                  {String(index + 1).padStart(2, "0")}
                </span>
                <span className="mt-1 block text-sm font-medium text-foreground">{output}</span>
              </li>
            ))}
          </ul>
        </section>
      </main>
    </PublicAppShell>
  );
}
