/**
 * Phase 9E deterministic fixtures. Hand-authored, never model-produced and
 * never generated by calling the adapter under test.
 *
 * All companies, customers and amounts are fictional.
 */

import { GUIDANCE_CARDS, GUIDANCE_REGISTRY_HASH } from "@/lib/arc/guidance/registry";
import type { GuidancePack } from "@/lib/arc/guidance/types";

import { AI_OUTPUT_SCHEMA_VERSION, type AiContractAnalysis } from "../schema";

export const RUN_ID = "run-00000000-0000-4000-8000-000000000001";

export function guidancePackFixture(): GuidancePack {
  return {
    registryHash: GUIDANCE_REGISTRY_HASH,
    cards: [...GUIDANCE_CARDS],
    inclusions: GUIDANCE_CARDS.map((card) => ({
      cardId: card.id,
      reason: "core" as const,
      matchedSignals: [],
    })),
  };
}

const DOC = "doc-fixture-1";

function cite(page: number, excerpt: string) {
  return {
    documentId: DOC,
    pageStart: page,
    pageEnd: page,
    evidenceMode: "text" as const,
    excerpt,
  };
}

function judgment(
  outcome: "yes" | "no" | "unknown",
  rationale: string,
  reviewState: AiContractAnalysis["contractAssessment"]["collectibility"]["reviewState"] = "supported",
) {
  return { outcome, rationale, citations: [cite(1, "Agreement")], guidanceIds: [1], reviewState };
}

function fact(value: string | null, rationale: string) {
  return {
    value,
    rationale,
    citations: [cite(1, "Agreement")],
    guidanceIds: [] as number[],
    reviewState: "supported" as const,
  };
}

/* ------------------------------------------- Fixture A — complete simple SaaS */

export function fixtureAAnalysis(): AiContractAnalysis {
  return {
    schemaVersion: AI_OUTPUT_SCHEMA_VERSION,
    analysisSummary: "Single-element annual hosted SaaS subscription.",
    logicalDocuments: [
      {
        semanticKey: "document:order-form",
        documentType: "order_form",
        title: "Order Form",
        effectiveDate: "2027-01-01",
        relationshipToAgreement: "The only contract document.",
        citations: [cite(1, "Order Form")],
        reviewState: "supported",
      },
    ],
    contractAssessment: {
      parties: [
        {
          semanticKey: "party:customer",
          name: "Redwood Retail",
          role: "customer",
          citations: [cite(1, "Redwood Retail")],
          reviewState: "supported",
        },
      ],
      contractReference: fact(null, "The order form states no reference number."),
      contractEffectiveDate: fact("2027-01-01", "Stated effective date."),
      contractTerm: fact("12 months", "Stated term."),
      approvalAndCommitment: judgment("yes", "Both parties executed the order form."),
      identifiableRights: judgment("yes", "Access rights are specified."),
      identifiablePaymentTerms: judgment("yes", "Annual fee payable net thirty days."),
      commercialSubstance: judgment("yes", "Cash flows change as a result of the contract."),
      collectibility: judgment("yes", "The customer is an established paying account."),
      terminationRights: fact(null, "No termination for convenience is stated."),
      renewalTerms: fact(null, "No automatic renewal is stated."),
      currency: fact("USD", "Amounts are stated in US dollars."),
    },
    promises: [
      {
        semanticKey: "promise:saas",
        description: "Annual hosted SaaS service",
        promiseType: "hosted_service",
        otherPromiseTypeDescription: null,
        explicitOrImplicit: "explicit",
        distinctCapableOfBeingDistinct: "yes",
        distinctSeparatelyIdentifiable: "yes",
        distinctConclusion: "yes",
        distinctnessRationale: "Benefit available on its own; not significantly integrated.",
        citations: [cite(1, "hosted service")],
        guidanceIds: [11],
        reviewState: "supported",
      },
    ],
    performanceObligations: [
      {
        semanticKey: "po:saas",
        promiseKeys: ["promise:saas"],
        description: "SaaS subscription",
        groupingRationale: "Single distinct hosted service.",
        satisfactionPattern: "over_time",
        recognitionRationale: "The customer simultaneously receives and consumes the service.",
        citations: [cite(1, "hosted service")],
        guidanceIds: [11],
        reviewState: "supported",
      },
    ],
    transactionPrice: {
      currency: fact("USD", "Amounts are stated in US dollars."),
      fixedConsiderationInput: "120000",
      fixedConsiderationRationale: "Annual fee stated in the order form.",
      fixedConsiderationCitations: [cite(1, "120,000")],
      variableConsiderationComponents: [],
      financingAssessment: judgment("no", "Payment occurs within one year of transfer."),
      noncashConsideration: judgment("no", "Consideration is entirely cash."),
      considerationPayableToCustomer: judgment("no", "No amounts are payable to the customer."),
      transactionPriceConclusion: {
        conclusion: "The transaction price is the fixed annual fee.",
        rationale: "No variable consideration is present.",
        citations: [cite(1, "120,000")],
        guidanceIds: [25],
        reviewState: "supported",
      },
    },
    sspAndAllocation: {
      relativeAllocationApplicable: judgment("no", "A single performance obligation exists."),
      items: [
        {
          semanticKey: "ssp:saas",
          appliesToKey: "po:saas",
          observableSspEvidence: "observable",
          observedAmountInput: "120000",
          proposedMethod: "observable_price",
          methodRationale: "Observable standalone renewal pricing.",
          missingInformation: "None.",
          citations: [cite(1, "120,000")],
          guidanceIds: [44],
          reviewState: "supported",
        },
      ],
      discountOrVariableAllocationConsiderations: "No discount is stated.",
    },
    recognitionProposals: [
      {
        performanceObligationKey: "po:saas",
        satisfactionPattern: "over_time",
        recognitionMethod: "ratable_over_time",
        serviceStartDate: "2027-01-01",
        serviceEndDate: "2027-12-31",
        measureDescription: "Time elapsed.",
        recognitionEventDescription: null,
        recognitionDateIfContractuallyDeterminable: null,
        rationale: "Customer simultaneously receives and consumes the hosted service.",
        citations: [cite(1, "term")],
        guidanceIds: [58],
        reviewState: "supported",
      },
    ],
    contractModifications: {
      hasModification: "no",
      effectiveDate: null,
      addedGoodsOrServices: null,
      addedGoodsDistinct: "unknown",
      priceIncreaseInput: null,
      priceReflectsSsp: "unknown",
      remainingGoodsDistinct: "unknown",
      treatmentCandidate: "not_applicable",
      rationale: "No amendment is present.",
      citations: [cite(1, "Order Form")],
      guidanceIds: [],
      reviewState: "supported",
    },
    billingTerms: [
      {
        semanticKey: "billing:annual-advance",
        description: "Annual advance invoice.",
        billingTiming: "advance",
        frequency: "annual",
        invoiceTrigger: "Start of the subscription term.",
        amountOrRateInput: "120000",
        paymentTermsDays: 30,
        dueDateRule: "Net 30 from invoice date.",
        citations: [cite(1, "Net 30")],
        reviewState: "supported",
      },
    ],
    projectedCollectionAssumptions: {
      contractualDueDateBasis: "invoice_date_plus_terms",
      paymentTermsDays: 30,
      basisExplanation: "Invoices are payable net thirty days from invoice date.",
      citations: [cite(1, "Net 30")],
      reviewState: "supported",
    },
    additionalTopics: [],
    issues: [],
  };
}

/* ------------------------------ Fixture F — multi-element / manual overlap */

/**
 * Two promises, two performance obligations and a semantic promise → PO
 * mapping. `secondServicePeriod` lets a test choose whether the two
 * performance obligations share one unambiguous contract service period or
 * describe two different ones.
 */
export function fixtureMultiElementAnalysis(
  secondServicePeriod: { start: string; end: string } = {
    start: "2027-01-01",
    end: "2027-12-31",
  },
): AiContractAnalysis {
  const analysis = fixtureAAnalysis();
  const promise = analysis.promises[0]!;
  const po = analysis.performanceObligations[0]!;
  const proposal = analysis.recognitionProposals[0]!;
  const ssp = analysis.sspAndAllocation.items[0]!;

  analysis.promises = [
    promise,
    {
      ...promise,
      semanticKey: "promise:support",
      description: "Premium support services",
      distinctnessRationale: "Support is sold separately and is not integrated with the platform.",
    },
  ];
  analysis.performanceObligations = [
    po,
    {
      ...po,
      semanticKey: "po:support",
      promiseKeys: ["promise:support"],
      description: "Premium support",
      groupingRationale: "A single distinct support service.",
    },
  ];
  analysis.recognitionProposals = [
    proposal,
    {
      ...proposal,
      performanceObligationKey: "po:support",
      serviceStartDate: secondServicePeriod.start,
      serviceEndDate: secondServicePeriod.end,
      rationale: "The customer simultaneously receives and consumes the support service.",
    },
  ];
  analysis.sspAndAllocation.items = [
    ssp,
    {
      ...ssp,
      semanticKey: "ssp:support",
      appliesToKey: "po:support",
      observedAmountInput: "30000",
      methodRationale: "Observable standalone support renewal pricing.",
    },
  ];
  analysis.transactionPrice.fixedConsiderationInput = "150000";
  return analysis;
}
