/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AnalysisRouteRouteImport } from './routes/analysis/route'
import { Route as AnalysisRouteImport } from './routes/analysis'
import { Route as EngineCheckRouteImport } from './routes/engine-check'
import { Route as AnalysisIndexRouteImport } from './routes/analysis/index'
import { Route as AnalysisDocumentsRouteImport } from './routes/analysis/documents'
import { Route as AnalysisScheduleRouteImport } from './routes/analysis/schedule'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalysisRouteRoute = AnalysisRouteRouteImport.update({
  id: '/analysis',
  path: '/analysis',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalysisRoute = AnalysisRouteImport.update({
  id: '/analysis',
  path: '/analysis',
  getParentRoute: () => rootRouteImport,
} as any)
const EngineCheckRoute = EngineCheckRouteImport.update({
  id: '/engine-check',
  path: '/engine-check',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalysisIndexRoute = AnalysisIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AnalysisRoute,
} as any)
const AnalysisDocumentsRoute = AnalysisDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => AnalysisRoute,
} as any)
const AnalysisScheduleRoute = AnalysisScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => AnalysisRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analysis': typeof AnalysisRouteWithChildren
  '/engine-check': typeof EngineCheckRoute
  '/analysis/documents': typeof AnalysisDocumentsRoute
  '/analysis/schedule': typeof AnalysisScheduleRoute
  '/analysis/': typeof AnalysisIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analysis': typeof AnalysisIndexRoute
  '/engine-check': typeof EngineCheckRoute
  '/analysis/documents': typeof AnalysisDocumentsRoute
  '/analysis/schedule': typeof AnalysisScheduleRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analysis': typeof AnalysisRouteWithChildren
  '/engine-check': typeof EngineCheckRoute
  '/analysis/documents': typeof AnalysisDocumentsRoute
  '/analysis/schedule': typeof AnalysisScheduleRoute
  '/analysis/': typeof AnalysisIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analysis'
    | '/engine-check'
    | '/analysis/documents'
    | '/analysis/schedule'
    | '/analysis/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analysis'
    | '/engine-check'
    | '/analysis/documents'
    | '/analysis/schedule'
  id:
    | '__root__'
    | '/'
    | '/analysis'
    | '/engine-check'
    | '/analysis/documents'
    | '/analysis/schedule'
    | '/analysis/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalysisRouteRoute: typeof AnalysisRouteRoute
  AnalysisRoute: typeof AnalysisRouteWithChildren
  EngineCheckRoute: typeof EngineCheckRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analysis': {
      id: '/analysis'
      path: '/analysis'
      fullPath: '/analysis'
      preLoaderRoute: typeof AnalysisRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analysis': {
      id: '/analysis'
      path: '/analysis'
      fullPath: '/analysis'
      preLoaderRoute: typeof AnalysisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/engine-check': {
      id: '/engine-check'
      path: '/engine-check'
      fullPath: '/engine-check'
      preLoaderRoute: typeof EngineCheckRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analysis/': {
      id: '/analysis/'
      path: '/'
      fullPath: '/analysis/'
      preLoaderRoute: typeof AnalysisIndexRouteImport
      parentRoute: typeof AnalysisRoute
    }
    '/analysis/documents': {
      id: '/analysis/documents'
      path: '/documents'
      fullPath: '/analysis/documents'
      preLoaderRoute: typeof AnalysisDocumentsRouteImport
      parentRoute: typeof AnalysisRoute
    }
    '/analysis/schedule': {
      id: '/analysis/schedule'
      path: '/schedule'
      fullPath: '/analysis/schedule'
      preLoaderRoute: typeof AnalysisScheduleRouteImport
      parentRoute: typeof AnalysisRoute
    }
  }
}

interface AnalysisRouteChildren {
  AnalysisDocumentsRoute: typeof AnalysisDocumentsRoute
  AnalysisScheduleRoute: typeof AnalysisScheduleRoute
  AnalysisIndexRoute: typeof AnalysisIndexRoute
}

const AnalysisRouteChildren: AnalysisRouteChildren = {
  AnalysisDocumentsRoute: AnalysisDocumentsRoute,
  AnalysisScheduleRoute: AnalysisScheduleRoute,
  AnalysisIndexRoute: AnalysisIndexRoute,
}

const AnalysisRouteWithChildren = AnalysisRoute._addFileChildren(
  AnalysisRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalysisRouteRoute: AnalysisRouteRoute,
  AnalysisRoute: AnalysisRouteWithChildren,
  EngineCheckRoute: EngineCheckRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
