/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AnalysisRouteRouteImport } from './routes/analysis/route'
import { Route as EngineCheckRouteImport } from './routes/engine-check'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as RecentRouteImport } from './routes/recent'
import { Route as SitemapRouteImport } from './routes/sitemap'
import { Route as AuthenticatedAccountRouteImport } from './routes/_authenticated/account'
import { Route as AuthenticatedWorkspaceRouteImport } from './routes/_authenticated/workspace'
import { Route as AnalysisIndexRouteImport } from './routes/analysis/index'
import { Route as AnalysisBalancesRouteImport } from './routes/analysis/balances'
import { Route as AnalysisDocumentsRouteImport } from './routes/analysis/documents'
import { Route as AnalysisJournalsRouteImport } from './routes/analysis/journals'
import { Route as AnalysisReviewRouteImport } from './routes/analysis/review'
import { Route as AnalysisScheduleRouteImport } from './routes/analysis/schedule'
import { Route as AnalysisNewRouteImport } from './routes/analysis_.new'
import { Route as AuthIndexRouteImport } from './routes/auth/index'
import { Route as AuthCallbackRouteImport } from './routes/auth/callback'
import { Route as ApiPublicMaintenanceRouteImport } from './routes/api/public/maintenance'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalysisRouteRoute = AnalysisRouteRouteImport.update({
  id: '/analysis',
  path: '/analysis',
  getParentRoute: () => rootRouteImport,
} as any)
const EngineCheckRoute = EngineCheckRouteImport.update({
  id: '/engine-check',
  path: '/engine-check',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const RecentRoute = RecentRouteImport.update({
  id: '/recent',
  path: '/recent',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapRoute = SitemapRouteImport.update({
  id: '/sitemap',
  path: '/sitemap',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAccountRoute = AuthenticatedAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedWorkspaceRoute = AuthenticatedWorkspaceRouteImport.update({
  id: '/workspace',
  path: '/workspace',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AnalysisIndexRoute = AnalysisIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AnalysisRouteRoute,
} as any)
const AnalysisBalancesRoute = AnalysisBalancesRouteImport.update({
  id: '/balances',
  path: '/balances',
  getParentRoute: () => AnalysisRouteRoute,
} as any)
const AnalysisDocumentsRoute = AnalysisDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => AnalysisRouteRoute,
} as any)
const AnalysisJournalsRoute = AnalysisJournalsRouteImport.update({
  id: '/journals',
  path: '/journals',
  getParentRoute: () => AnalysisRouteRoute,
} as any)
const AnalysisReviewRoute = AnalysisReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => AnalysisRouteRoute,
} as any)
const AnalysisScheduleRoute = AnalysisScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => AnalysisRouteRoute,
} as any)
const AnalysisNewRoute = AnalysisNewRouteImport.update({
  id: '/analysis_/new',
  path: '/analysis/new',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/auth/',
  path: '/auth/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicMaintenanceRoute = ApiPublicMaintenanceRouteImport.update({
  id: '/api/public/maintenance',
  path: '/api/public/maintenance',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analysis': typeof AnalysisRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/engine-check': typeof EngineCheckRoute
  '/privacy': typeof PrivacyRoute
  '/recent': typeof RecentRoute
  '/sitemap': typeof SitemapRoute
  '/account': typeof AuthenticatedAccountRoute
  '/workspace': typeof AuthenticatedWorkspaceRoute
  '/analysis/balances': typeof AnalysisBalancesRoute
  '/analysis/documents': typeof AnalysisDocumentsRoute
  '/analysis/journals': typeof AnalysisJournalsRoute
  '/analysis/review': typeof AnalysisReviewRoute
  '/analysis/schedule': typeof AnalysisScheduleRoute
  '/analysis/new': typeof AnalysisNewRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/analysis/': typeof AnalysisIndexRoute
  '/auth/': typeof AuthIndexRoute
  '/api/public/maintenance': typeof ApiPublicMaintenanceRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/engine-check': typeof EngineCheckRoute
  '/privacy': typeof PrivacyRoute
  '/recent': typeof RecentRoute
  '/sitemap': typeof SitemapRoute
  '/account': typeof AuthenticatedAccountRoute
  '/workspace': typeof AuthenticatedWorkspaceRoute
  '/analysis/balances': typeof AnalysisBalancesRoute
  '/analysis/documents': typeof AnalysisDocumentsRoute
  '/analysis/journals': typeof AnalysisJournalsRoute
  '/analysis/review': typeof AnalysisReviewRoute
  '/analysis/schedule': typeof AnalysisScheduleRoute
  '/analysis/new': typeof AnalysisNewRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/analysis': typeof AnalysisIndexRoute
  '/auth': typeof AuthIndexRoute
  '/api/public/maintenance': typeof ApiPublicMaintenanceRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/analysis': typeof AnalysisRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/engine-check': typeof EngineCheckRoute
  '/privacy': typeof PrivacyRoute
  '/recent': typeof RecentRoute
  '/sitemap': typeof SitemapRoute
  '/_authenticated/account': typeof AuthenticatedAccountRoute
  '/_authenticated/workspace': typeof AuthenticatedWorkspaceRoute
  '/analysis/balances': typeof AnalysisBalancesRoute
  '/analysis/documents': typeof AnalysisDocumentsRoute
  '/analysis/journals': typeof AnalysisJournalsRoute
  '/analysis/review': typeof AnalysisReviewRoute
  '/analysis/schedule': typeof AnalysisScheduleRoute
  '/analysis_/new': typeof AnalysisNewRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/analysis/': typeof AnalysisIndexRoute
  '/auth/': typeof AuthIndexRoute
  '/api/public/maintenance': typeof ApiPublicMaintenanceRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analysis'
    | '/about'
    | '/engine-check'
    | '/privacy'
    | '/recent'
    | '/sitemap'
    | '/account'
    | '/workspace'
    | '/analysis/balances'
    | '/analysis/documents'
    | '/analysis/journals'
    | '/analysis/review'
    | '/analysis/schedule'
    | '/analysis/new'
    | '/auth/callback'
    | '/analysis/'
    | '/auth/'
    | '/api/public/maintenance'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/engine-check'
    | '/privacy'
    | '/recent'
    | '/sitemap'
    | '/account'
    | '/workspace'
    | '/analysis/balances'
    | '/analysis/documents'
    | '/analysis/journals'
    | '/analysis/review'
    | '/analysis/schedule'
    | '/analysis/new'
    | '/auth/callback'
    | '/analysis'
    | '/auth'
    | '/api/public/maintenance'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/analysis'
    | '/about'
    | '/engine-check'
    | '/privacy'
    | '/recent'
    | '/sitemap'
    | '/_authenticated/account'
    | '/_authenticated/workspace'
    | '/analysis/balances'
    | '/analysis/documents'
    | '/analysis/journals'
    | '/analysis/review'
    | '/analysis/schedule'
    | '/analysis_/new'
    | '/auth/callback'
    | '/analysis/'
    | '/auth/'
    | '/api/public/maintenance'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AnalysisRouteRoute: typeof AnalysisRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  EngineCheckRoute: typeof EngineCheckRoute
  PrivacyRoute: typeof PrivacyRoute
  RecentRoute: typeof RecentRoute
  SitemapRoute: typeof SitemapRoute
  AnalysisNewRoute: typeof AnalysisNewRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  AuthIndexRoute: typeof AuthIndexRoute
  ApiPublicMaintenanceRoute: typeof ApiPublicMaintenanceRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analysis': {
      id: '/analysis'
      path: '/analysis'
      fullPath: '/analysis'
      preLoaderRoute: typeof AnalysisRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/engine-check': {
      id: '/engine-check'
      path: '/engine-check'
      fullPath: '/engine-check'
      preLoaderRoute: typeof EngineCheckRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recent': {
      id: '/recent'
      path: '/recent'
      fullPath: '/recent'
      preLoaderRoute: typeof RecentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap': {
      id: '/sitemap'
      path: '/sitemap'
      fullPath: '/sitemap'
      preLoaderRoute: typeof SitemapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/account': {
      id: '/_authenticated/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AuthenticatedAccountRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/workspace': {
      id: '/_authenticated/workspace'
      path: '/workspace'
      fullPath: '/workspace'
      preLoaderRoute: typeof AuthenticatedWorkspaceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/analysis/': {
      id: '/analysis/'
      path: '/'
      fullPath: '/analysis/'
      preLoaderRoute: typeof AnalysisIndexRouteImport
      parentRoute: typeof AnalysisRouteRoute
    }
    '/analysis/balances': {
      id: '/analysis/balances'
      path: '/balances'
      fullPath: '/analysis/balances'
      preLoaderRoute: typeof AnalysisBalancesRouteImport
      parentRoute: typeof AnalysisRouteRoute
    }
    '/analysis/documents': {
      id: '/analysis/documents'
      path: '/documents'
      fullPath: '/analysis/documents'
      preLoaderRoute: typeof AnalysisDocumentsRouteImport
      parentRoute: typeof AnalysisRouteRoute
    }
    '/analysis/journals': {
      id: '/analysis/journals'
      path: '/journals'
      fullPath: '/analysis/journals'
      preLoaderRoute: typeof AnalysisJournalsRouteImport
      parentRoute: typeof AnalysisRouteRoute
    }
    '/analysis/review': {
      id: '/analysis/review'
      path: '/review'
      fullPath: '/analysis/review'
      preLoaderRoute: typeof AnalysisReviewRouteImport
      parentRoute: typeof AnalysisRouteRoute
    }
    '/analysis/schedule': {
      id: '/analysis/schedule'
      path: '/schedule'
      fullPath: '/analysis/schedule'
      preLoaderRoute: typeof AnalysisScheduleRouteImport
      parentRoute: typeof AnalysisRouteRoute
    }
    '/analysis_/new': {
      id: '/analysis_/new'
      path: '/analysis/new'
      fullPath: '/analysis/new'
      preLoaderRoute: typeof AnalysisNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/': {
      id: '/auth/'
      path: '/auth'
      fullPath: '/auth/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/maintenance': {
      id: '/api/public/maintenance'
      path: '/api/public/maintenance'
      fullPath: '/api/public/maintenance'
      preLoaderRoute: typeof ApiPublicMaintenanceRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAccountRoute: typeof AuthenticatedAccountRoute
  AuthenticatedWorkspaceRoute: typeof AuthenticatedWorkspaceRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAccountRoute: AuthenticatedAccountRoute,
  AuthenticatedWorkspaceRoute: AuthenticatedWorkspaceRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface AnalysisRouteRouteChildren {
  AnalysisBalancesRoute: typeof AnalysisBalancesRoute
  AnalysisDocumentsRoute: typeof AnalysisDocumentsRoute
  AnalysisJournalsRoute: typeof AnalysisJournalsRoute
  AnalysisReviewRoute: typeof AnalysisReviewRoute
  AnalysisScheduleRoute: typeof AnalysisScheduleRoute
  AnalysisIndexRoute: typeof AnalysisIndexRoute
}

const AnalysisRouteRouteChildren: AnalysisRouteRouteChildren = {
  AnalysisBalancesRoute: AnalysisBalancesRoute,
  AnalysisDocumentsRoute: AnalysisDocumentsRoute,
  AnalysisJournalsRoute: AnalysisJournalsRoute,
  AnalysisReviewRoute: AnalysisReviewRoute,
  AnalysisScheduleRoute: AnalysisScheduleRoute,
  AnalysisIndexRoute: AnalysisIndexRoute,
}

const AnalysisRouteRouteWithChildren = AnalysisRouteRoute._addFileChildren(
  AnalysisRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AnalysisRouteRoute: AnalysisRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  EngineCheckRoute: EngineCheckRoute,
  PrivacyRoute: PrivacyRoute,
  RecentRoute: RecentRoute,
  SitemapRoute: SitemapRoute,
  AnalysisNewRoute: AnalysisNewRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  AuthIndexRoute: AuthIndexRoute,
  ApiPublicMaintenanceRoute: ApiPublicMaintenanceRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
