// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nsmxezhuwkzfvoijjyoi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5zbXhlemh1d2t6ZnZvaWpqeW9pIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODg5MjMxNjcsImV4cCI6MjEwNDQ5OTE2N30.V9wleJL04UPORW1xBZRJEh6wlXxI9eLzgsnz-2Djweo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: typeof window !== 'undefined' ? localStorage : undefined,
    persistSession: true,
    autoRefreshToken: true,
  }
});